### ISSUE TITLE
Add footer with copyright notice, using JavaScript

### ISSUE THREAD

**Issue by ryexley** [GSterie/gsterie-website#1]
Add a script or JavaScript function to your site, that adds a dynamic footer to your web site, using the current year. Take the example of the GitHub footer here, which has this in the footer:

<img width="132" alt="image" src="https://github.com/GSterie/gsterie-website/assets/173844/cc297f59-ea63-4187-897d-9f17f1326580">

With the exception that, for yours, it should read "Griffin Sterie", instead of "GitHub, Inc.".

**Comment by ryexley** [comment]
As a bonus exercise, if you feel like tackling this as well, see if you can figure out how to add this new feature in a "working branch", and submit the changes for this new features as a Pull Request through GitHub. You might try looking through TreeHouse to see if they have any courses on using git and/or GitHub for this.

**Comment by GSterie** [comment]
The footer is done.

**Comment by GSterie** [comment]
But it was inside the HTML file. It did not want to work on a separate file in VSCode for some reason. I didn't upload an index.js file yet.

**Comment by ryexley** [comment]
Did you check to see if Treehouse had any content on git or GitHub and pull requests?

**Comment by ryexley** [comment]
> It did not want to work on a separate file in VSCode for some reason.

I assume you would have shared why if you knew, but can you at least share what issue you were running into here? Like, what does "for some reason" mean? Was VS Code throwing errors, or giving you some kind of issue? Would be ideal to get all JS logic into separate files. This is called the "separation of concerns" principle.

**Comment by GSterie** [comment]
VSCode wasn't throwing any issues, and when I tried the same, _working_, code in my liked JS file the text would not show up, but in a new script tag in the HTML. And no, I didn't check for GitHub content on Treehouse. I will make sure to try again.

**Comment by GSterie** [comment]
I added a separate JS file to my repository, and the same issue occurred. It is the same code from the script tags in the HTML copied and pasted, and if you check my website, the date is gone.

**Comment by GSterie** [comment]
Treehouse doesn't have any git/GitHub classes

**Comment by ryexley** [comment]
> Treehouse doesn't have any git/GitHub classes

I'll see if I can find something for that. I'll take a look with you next time we get a chance and see if we can figure out why the external / script referenced file approach isn't working.

**Comment by GSterie** [comment]
Koo...

**Comment by GSterie** [comment]
found issue and started pull request

**Comment by GSterie** [comment]
Merged pull request
